project_name: wait-for
before:
  hooks:
    - go mod tidy
builds:
  - env:
      - CGO_ENABLED=0
    goarch:
      - amd64
      - 386
    goos:
      - linux
      - windows
      - darwin
    binary: 'wait-for-{{ .Os }}-{{ .Arch }}'
    ldflags:
      - "-w"
      - "-s"
      - "-X main.version={{ .Version }}"
    hooks:
      post:
        - 'upx -9 {{ .Path }}'
